language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
  - pip install pytest
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,W292 src"
  - pyflakes -x W src
script:
  - py.test
